### ISSUE TITLE
removing "rm -rf /var/lib/storageos" unable to delete  /var/lib/storageos/volumes

### ISSUE THREAD

**Issue by SKD-SKD** [storageos/cluster-operator#121]
```
"rm -rf /var/lib/storageos" unable to delete  /var/lib/storageos/volumes ->  **in use** 

i login to every node to "rm -rf  /var/lib/storageos/*"
i need to  do "fusermount -u /var/lib/storageos/volumes" before "/var/lib/storageos/*" can be deleted  
```

**Comment by avestuk** [comment]
Hi @SKD-SKD, /var/lib/storageos/volumes is mounted by the kubelet and needs to be unmounted before /var/lib/storageos can be deleted. Currenlty the operator cleanup job does not do the umount which is something that I will raise a request to get fixed. 

In the meantime I'd suggest using a bash for loop to ssh into each node, umount storageos and then delete /var/lib/storageos.

**Comment by SKD-SKD** [comment]
sure i will use :
```
fusermount -u /var/lib/storageos/volumes
rm -rf /var/lib/storageos
```
on every node 
thank you
