### ISSUE TITLE
Expand PersistentVolumes in k8s

### ISSUE THREAD

**Issue by blacs30** [storageos/cluster-operator#152]
On this page [https://storageos.com/why-storageos/](https://storageos.com/why-storageos/) I read something about `volume resize`.

However I wasn't able to find further documentation about it.

I am testing StorageOS on Kubernetes, both latest version as of writing. 
According to the Kubernetes documentation StorageOS doesn't support expanding (yet) [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims)

Can you give more insights into this topic please? Is it already possible on k8s? If not is it coming soon?

Thanks a lot!

**Comment by actionbuddha** [comment]
Hi, thanks for pointing this out. We don't yet have volume resize in the product, but it is coming in a future release. Please keep an eye on our changelog for more details! We'll amend the website accordingly.
