### ISSUE TITLE
Error on creation of PVC

### ISSUE THREAD

**Issue by includeamin** [storageos/cluster-operator#211]
```
2019-12-04T18:39:28.264Z	INFO	storageos.node	Failed to sync node labels	{"Request.Namespace": "", "Request.Name": "chichi-master-server", "error": "API error (Server failed to process your request. Was the data correct?): node not found"
```

**Comment by avestuk** [comment]
Hi @includeamin this error is a result of the StorageOS operator attempting to sync k8s node labels for a node that is not running StorageOS and as such is not part of the StorageOS cluster. The error is nothing to worry about and does not relate to the creation of your PVC. 

We are aware of this issue and are working on a fix.

**Comment by includeamin** [comment]
it was working properly but after an hour not work anymore.
I had MongoDB deployment with that PVC.

**Comment by avestuk** [comment]
Could you send an email to us with the troubleshooting information requested on the page below? If you could upload the cluster diagnostic that'd also be very helpful. 

https://docs.storageos.com/docs/support/contactus

**Comment by includeamin** [comment]
sorry, I don't have that cluster anymore.  after that, I set up a fresh cluster.
