### ISSUE TITLE
[FEATURE] UI show volumes for all namespaces

### ISSUE THREAD

**Issue by blacs30** [storageos/cluster-operator#256]
Running storageos 2.0.0, migrated now also to a SSD only server. 
Startup of the same statefulsets feels like factor x20.

One thing I noticed is that there is no option to show volumes for all namespaces on one page. 

I think it would make sense to have this option for the _nodes_ view 
(if a namespace workload is on that node) and the _volumes_ view

**Comment by Arau** [comment]
Hi @blacs30,

thank you for opening the feature request. We really appreciate it! 

You are completely right about the name spaces. In fact, that feature request is already in our Feedback pipeline to be improved. So I'm adding more weight to it 😃 . 

We have put the feature in the CLI already, and we are planning to add that feature in the UI too. If for the time being, that helps, the CLI has the `--all-namespaces` flag. So `storageos get volumes --all-namespaces`.
