### ISSUE TITLE
Node metrics in v2

### ISSUE THREAD

**Issue by blacs30** [storageos/cluster-operator#289]
First of all: thanks you for this great product.

Using StorageOS in a small private cluster for more than 2 years I believe and love it. Currently running v2.3.0, installed via helm chart.

I see that on the node pod an exporter starts on port `9721`, it's secured using the default user/password and is not documented at all. It contains a lot of interesting metrics but also not those similar to the old version.
The node pod on port `5705` doesn't have a `/metrics` endpoint any longer with v2 if I'm correct.

Question:
-> I am wondering though, maybe I overlook something, are there metrics available for the node in the [same way as for v1.2.0+](https://grafana.com/grafana/dashboards/10093) which show the IOPS etc?

**Comment by StellaEngle** [comment]
Hi @blacs30 

We don't have that feature yet for v2.x but we are working on it to release it very soon.

Very glad to hear you like the product!

Thank you
