### ISSUE TITLE
Add daemonset node tolerations support

### ISSUE THREAD

**Issue by tobiaskohlbau** [storageos/cluster-operator#58]
We've the desire to deploy specific storage nodes. In order to achieve this we set a node taint to avoid scheduling any workload pods onto them. In order to schedule the storageos pods onto them, the operator needs to inject a node toleration in the daemonset. I would like to see this be supported by adding support in similar way as #19 did for node selectors.

What are your thoughts about this?
If you're willing to support this, I could find some time to workout a draft PR based on the code of #19.

**Comment by Arau** [comment]
Hi @tobiaskohlbau,

that makes complete sense. We are adding this into the roadmap. StorageOS cluster-operator is under heavy development to add more functionality and support, if for the moment and until we add the tolerations, you want to be able to edit the DaemonSet you can use a different method to install, https://github.com/storageos/deploy/tree/master/k8s/deploy-storageos/standard. That method lets you edit the manifests, for instance https://github.com/storageos/deploy/blob/master/k8s/deploy-storageos/standard/manifests/040_daemonset.yaml_template.

**Comment by tobiaskohlbau** [comment]
Hello @Arau I've started implementing this. 

See #59 for more information and a draft pull request.

For my tests I've setup a 1 master 2 worker node cluster. I've encountered weird behaviour after adding node tolerations and *not* adding this into the CR the storageos container can't connect to it's embedded etcd. Is this a limitation from storageos that single nodes do not work, or did I messed something up?
If I add the toleration back into the CR and redeploy the storageos containers start just fine.

**Comment by Arau** [comment]
Hi @tobiaskohlbau,

the etcd is a datastore that ensures data consistency across its instances. To do so, it requires quorum. Hence an odd number of nodes. In your case, 2 workers are not enough to have quorum. You need either one or three nodes. 
Have you deployed StorageOS in the master? If so, the Pod in the master usually can't start making the discovery process unfit to start the rest of the nodes. 

https://docs.storageos.com/docs/platforms/kubernetes/troubleshoot/install#peer-discovery---pod-allocation
