### ISSUE TITLE
Add CRD spec and status descriptors in CSV

### ISSUE THREAD

**Issue by darkowlzz** [storageos/cluster-operator#98]
All the fields in spec and status should have human readable descriptions.
Examples of a few spec and status field description are [here](https://github.com/storageos/cluster-operator/blob/v1.0.0/deploy/olm/storageos/storageos.v0.0.12.clusterserviceversion.yaml#L257-L280).
All the fields in [spec](https://github.com/storageos/cluster-operator/blob/master/pkg/apis/storageos/v1/storageoscluster_types.go#L69-L159) and [status](https://github.com/storageos/cluster-operator/blob/master/pkg/apis/storageos/v1/storageoscluster_types.go#L162-L171) should have their description under the `StorageOSCluster` definition.

Likewise for [upgrade](https://github.com/storageos/cluster-operator/blob/master/pkg/apis/storageos/v1/storageosupgrade_types.go) and [job](https://github.com/storageos/cluster-operator/blob/master/pkg/apis/storageos/v1/job_types.go) CRDs.

These descriptions count towards the operator scorecard points.

**Comment by croomes** [comment]
Fixed in https://github.com/storageos/cluster-operator/pull/104
